service: user-notes

custom:
  secrets: ${file(env.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-central-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB: ${self:custom.secrets.DB}
    AWS_SECRETKEY: ${self:custom.secrets.AWS_SECRETKEY}
    AWS_ACCESSKEY: ${self:custom.secrets.AWS_ACCESSKEY}
    AWS_REGION: ${self:custom.secrets.AWS_REGION}
    AWS_BUCKET: ${self:custom.secrets.AWS_BUCKET}
    AWS_DIRECTORY_PATH: ${self:custom.secrets.AWS_DIRECTORY_PATH}

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline